## 1.Arithmetic Operators

In [1]:
# Input the numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# sum
sum_result = num1 + num2

# difference
diff_result = num1 - num2

# product
prod_result = num1 * num2

# quotient
quot_result = num1 / num2

# Print the results
print("Sum:", sum_result)
print("Difference:", diff_result)
print("Product:", prod_result)
print("Quotient:", quot_result)

Enter the first number:  12
Enter the second number:  -15


Sum: -3.0
Difference: 27.0
Product: -180.0
Quotient: -0.8


## 2. Comparison Operators

In [2]:
# Input the numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Compare the numbers
if num1 > num2:
    print(num1, "is greater than", num2)
elif num1 < num2:
    print(num1, "is less than", num2)
else:
    print(num1, "is equal to", num2)

Enter the first number:  12
Enter the second number:  15


12.0 is less than 15.0


## 3. Assignment Operators

In [7]:
# Input the initial value
initial_value = float(input("Enter the initial value: "))

# Apply different assignment operators
initial_value += 5  # Add 5 to the initial value
print("After += 5, the value is:", initial_value)

initial_value -= 3  # Subtract 3 from the current value
print("After -= 3, the value is:", initial_value)

initial_value *= 2  # Multiply the current value by 2
print("After *= 2, the value is:", initial_value)

initial_value /= 4  # Divide the current value by 4
print("After /= 4, the value is:", initial_value)

initial_value **= 3  # Raise the current value to the power of 3
print("After **= 3, the value is:", initial_value)

initial_value //= 2  # Perform floor division of the current value by 2
print("After //= 2, the value is:", initial_value)

initial_value %= 3  # Take the modulus of the current value by 3
print("After %= 3, the value is:", initial_value)

Enter the initial value:  6


After += 5, the value is: 11.0
After -= 3, the value is: 8.0
After *= 2, the value is: 16.0
After /= 4, the value is: 4.0
After **= 3, the value is: 64.0
After //= 2, the value is: 32.0
After %= 3, the value is: 2.0


## 4. Comparison Operators

In [8]:
# Input the age
age = int(input("Enter your age: "))

# Check eligibility to vote
if age >= 18:
    print("You are eligible to vote!")
else:
    print("You are not eligible to vote yet.")

Enter your age:  15


You are not eligible to vote yet.


## 5. If-else Statements

In [9]:
# Input the number
number = float(input("Enter a number: "))

# Check if the number is positive, negative, or zero
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter a number:  10


The number is positive.


## 6. For Loops

In [10]:
# Input the string
input_string = input("Enter a string: ")

# Print each character on a separate line
for character in input_string:
    print(character)

Enter a string:  Hamed


H
a
m
e
d


## 7. While Loops

In [11]:
# Input the number
number = int(input("Enter a number: "))

# Initialize a counter
counter = 0

# Print even numbers up to the input number
while counter <= number:
    if counter % 2 == 0:
        print(counter)
    counter += 1

Enter a number:  15


0
2
4
6
8
10
12
14


## 8. Control Flow with Lists and Conditions

In [12]:
# Input the list of words
words = input("Enter a list of words, separated by spaces: ").split()

for word in words:
    if word.startswith('a') or word.startswith('A'):
        print("Length of", word, ":", len(word))

Enter a list of words, separated by spaces:  ahmad taghi hasan Arash Armita ahan


Length of ahmad : 5
Length of Arash : 5
Length of Armita : 6
Length of ahan : 4


## 9. Basic List Operations

In [13]:
# first list
list1 = [1, 2, 3, 4, 5]

# second list
list2 = [6, 7, 8, 9, 10]

# Concatenate the two lists
concatenated_list = list1 + list2

print("Concatenated List:", concatenated_list)

Concatenated List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## 10. Accessing List Elements

In [14]:
numbers = [10, 20, 30, 40, 50]

sum_of_elements = numbers[0] + numbers[-1]

print("Sum of the first and last elements:", sum_of_elements)

Sum of the first and last elements: 60


## 11. Modifying Lists

In [15]:
# list of numbers
numbers = [10, 20, 30, 40, 50]

# Change the value of the third element
numbers[2] = 35

print("Updated list of numbers:", numbers)

Updated list of numbers: [10, 20, 35, 40, 50]


## 12. Slicing and Sublists

In [16]:

strings = ["apple", "banana", "cherry", "date", "elderberry"]

# Create a sublist containing the last two elements
sublist = strings[-2:]

print("Sublist containing the last two elements:", sublist)

Sublist containing the last two elements: ['date', 'elderberry']


## 13. Basic Tuple Operations

In [19]:
my_tuple = ("apple", "banana", "cherry", "date", "elderberry")

# method 1
print("method 1\n")
for element in reversed(my_tuple):
    print(element)

# method 2
print("\n\nmethod 2\n")
for element in my_tuple[::-1]:
    print(element)

method 1

elderberry
date
cherry
banana
apple


method 2

elderberry
date
cherry
banana
apple


## 14. Accessing Tuple Elements

In [20]:
my_tuple = (10, 20, 30, 40, 50)

sum_of_elements = my_tuple[0] + my_tuple[-1]

print("Sum of the first and last elements:", sum_of_elements)

Sum of the first and last elements: 60


## 15. Modifying Tuples

In [21]:
# tuple of numbers
my_tuple = (10, 20, 30, 40, 50)

# Convert the tuple to a list
my_list = list(my_tuple)

# Change the value of the third element
my_list[2] = 35

# Convert the list back to a tuple
my_tuple = tuple(my_list)

# Print the updated tuple
print("Updated tuple of numbers:", my_tuple)

Updated tuple of numbers: (10, 20, 35, 40, 50)


## 16. Slicing and Subtuples

In [22]:
# tuple of strings
my_tuple = ("apple", "banana", "cherry", "date", "elderberry")

# subtuple containing the last two elements
subtuple = my_tuple[-2:]

# Print the subtuple
print("Subtuple containing the last two elements:", subtuple)

Subtuple containing the last two elements: ('date', 'elderberry')


## 17. Basic Dictionary Operations

In [23]:
# product dictionary
product = {
    "name": "Laptop",
    "price": 999.99,
    "quantity": 5
}

# Print the dictionary
print("Product dictionary:", product)

Product dictionary: {'name': 'Laptop', 'price': 999.99, 'quantity': 5}


## 18. Accessing Dictionary Elements

In [24]:
# person dictionary
person = {
    "name": "Hamed Daneshvar",
    "age": 26,
    "occupation": "Software Engineer"
}

# Print the value associated with the "name" key
print("Person's name:", person["name"])

Person's name: Hamed Daneshvar


## 19. Modifying Dictionaries

In [25]:
# product dictionary
product = {
    "name": "Laptop",
    "price": 999.99,
    "quantity": 5
}

# Update the value associated with the "quantity" key
product["quantity"] = 10

# Print the updated dictionary
print("Updated product dictionary:", product)

Updated product dictionary: {'name': 'Laptop', 'price': 999.99, 'quantity': 10}


## 20. Adding and Removing Dictionary Entries

In [26]:
# empty dictionary
person = {}

# Add key-value pairs for "name" and "age"
person["name"] = "Hamed Daneshvar"
person["age"] = 26

# Print the dictionary
print("Person dictionary:", person)

Person dictionary: {'name': 'Hamed Daneshvar', 'age': 26}


## 21. Creating and Modifying Sets

In [37]:
# set with tuple product information
product_set = {("Laptop", 5), ("vacuum", 2)}

# Create a new empty set to store updated product information
new_product_set = set()

for product in product_set:
    name, quantity = product
    
    # Check if the product name is "Laptop"
    if name == "Laptop":
        quantity += 5
        product = name, quantity
        
    # Add the product tuple to the new set
    new_product_set.add(product)

# Print the updated product set
print(new_product_set)

{('vacuum', 2), ('Laptop', 10)}


## 22. Set Operations

In [38]:
# Create two sets of numbers
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

# Perform union operation to combine them
union_set = set1.union(set2)

# Print the resulting set
print("Union set:", union_set)

Union set: {1, 2, 3, 4, 5, 6}


## 23. Removing Set Elements

### a section

In [41]:
# set of numbers
number_set = {1, 2, 3, 4, 5}

# Remove a specific element using the remove() method
number_set.remove(3)

# Print the updated set
print("Updated set:", number_set)

Updated set: {1, 2, 4, 5}


### b section

In [42]:
# set of strings
string_set = {"apple", "banana", "orange", "grape"}

# Remove an element using the discard() method
string_set.discard("orange")

# Print the updated set
print("Updated set:", string_set)

Updated set: {'grape', 'banana', 'apple'}


## 24. String Operations

In [43]:
my_string = "Hello!"

# Repeat the string multiple times using the multiplication operator
repeated_string = my_string * 3

# Print the repeated string
print("Repeated string:", repeated_string)

Repeated string: Hello!Hello!Hello!


## 25. Accessing String Characters

In [44]:
my_string = "Hello, World!"

# Print the last character
print("Last character:", my_string[-1])

Last character: !


## 26. String Length and Slicing

In [48]:
my_string = "Hello, World!"

# Print the substring
print("Substring:", my_string[3:-2])

Substring: lo, Worl


## 27. Modifying Strings

In [49]:
my_string = "Hello, World!"

# Print the uppercase string
print("Uppercase string:", my_string.upper())

Uppercase string: HELLO, WORLD!


## 28. Function Basics

In [51]:
def calculate_area(length, width):
    area = length * width
    return area

# Print the result
print("Area:", calculate_area(5, 3))

Area: 15


## 29. Function Parameters and Arguments

In [52]:
def add_numbers(num1, num2):
    sum = num1 + num2
    return sum

# Print the result
print("Sum:", add_numbers(5, 3))

Sum: 8


## 30. Default Parameters

In [53]:
def calculate_power(number, exponent=2):
    power = number ** exponent
    return power

# Print the result
print("Power:", calculate_power(3, 4))

Power: 81


## 31. Lambda Functions

In [54]:
is_divisible_by_2 = lambda number: number % 2 == 0

# Check if the number 6 is divisible by 2
result = is_divisible_by_2(6)
print(result)  # Output: True

# Check if the number 9 is divisible by 2
result = is_divisible_by_2(9)
print(result)  # Output: False

True
False


## 32. Sum of List

In [55]:
def calculate_sum(numbers):
    total = 0
    for number in numbers:
        total += number

    return total


numbers = [1, 2, 3, 4, 5]
print("Sum:", calculate_sum(numbers))

Sum: 15


## 33. Factorial

In [56]:
def calculate_factorial(number):
    factorial = 1
    for i in range(1, number + 1):
        factorial *= i

    return factorial


# Print the result
print("Factorial:", calculate_factorial(5))

Factorial: 120


## 34. Counting Vowels

In [57]:
def count_vowels(input_string):
    vowel_count = 0
    for char in input_string.lower():
        if char in 'aeiou':
            vowel_count += 1

    return vowel_count


input_string = "Hello World"
print("Number of vowels:", count_vowels(input_string))

Number of vowels: 3


## 35. Fibonacci Sequence

In [76]:
def print_fibonacci_sequence(number):
    first = 0
    second = 1

    if number >= first:
        print(first)
    if number >= second:
        print(second)

    while (first + second) <= number:
        next_number = first + second
        print(next_number)
        
        first = second
        second = next_number


print("Fibonacci sequence:")
print_fibonacci_sequence(15)

Fibonacci sequence:
0
1
1
2
3
5
8
13


## 36. Factorial

In [75]:
def calculate_factorial(number):
    if number == 0:
        return 1

    return number * calculate_factorial(number - 1)

# Print the result
print("Factorial:", calculate_factorial(5))

Factorial: 120


## 37. Fibonacci Sequence

In [79]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1

    return fibonacci(n-1) + fibonacci(n-2)

# Print the result
print("Fibonacci sequence:", fibonacci(6))

Fibonacci sequence: 8


## 38. Divide by Zero

In [80]:
def divide_numbers(a, b):
    try:
        print("Result:", a / b)
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")


num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
divide_numbers(num1, num2)

Enter the first number:  5
Enter the second number:  0


Error: Division by zero is not allowed.


## 39. File Reading

In [82]:
def read_file(file_name):
    try:
        with open(file_name, 'r') as file:
            contents = file.read()
            print("File Contents:\n", contents)
    except FileNotFoundError:
        print("Error: File not found.")

file_name = input("Enter the file name: ")
read_file(file_name)

Enter the file name:  '.ipynb_checkpoints/FFCVS_Dec23_Course_Ex_silver_Python_Hamed_Daneshvar-checkpoint'


Error: File not found.


## 40. Input Validation

In [83]:
def get_positive_integer():
    while True:
        try:
            number = int(input("Enter a positive integer: "))
            if number <= 0:
                raise ValueError
            return number
        except ValueError:
            print("Error: Invalid input. Please enter a positive integer.")


print("Valid positive integer entered:", get_positive_integer())

Enter a positive integer:  -1


Error: Invalid input. Please enter a positive integer.


Enter a positive integer:  -2


Error: Invalid input. Please enter a positive integer.


Enter a positive integer:  0


Error: Invalid input. Please enter a positive integer.


Enter a positive integer:  1


Valid positive integer entered: 1


## 41. Index Error

In [86]:
numbers = []
for i in range(10):
    numbers.append(i)

def access_list(numbers):
    try:
        index = int(input("Enter an index to access: "))
        print("Value at index", index, "is", numbers[index])
    except IndexError:
        print("Error: Index out of range. Please enter a valid index.")

print(numbers)
access_list(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Enter an index to access:  10


Error: Index out of range. Please enter a valid index.


# numpy section

In [89]:
import numpy as np

## 42. Array Creation

In [93]:
array = np.zeros((3, 3), dtype=np.uint8)
print("Array:", array, sep="\n")

Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 43. Array Operations

In [100]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

result = array1 + array2

print("Array 1:")
print(array1, "\n")

print("Array 2:")
print(array2, "\n")

print("Result of element-wise addition:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Array 2:
[[10 20 30]
 [40 50 60]
 [70 80 90]] 

Result of element-wise addition:
[[11 22 33]
 [44 55 66]
 [77 88 99]]


## 44. Array Indexing and Slicing

In [98]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

subarray = array[:2, :2]

print("Array:")
print(array, "\n")

print("2x2 Subarray:")
print(subarray)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

2x2 Subarray:
[[1 2]
 [5 6]]


## 45. Array Shape and Reshaping

In [101]:
array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = array.reshape(2, 3)

print("Original Array:")
print(array, "\n")

print("Reshaped Array (2x3):")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6] 

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


## 46. Array Aggregation

In [103]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

column_means = np.mean(array, axis=0)

print("Array:")
print(array, "\n")

print("Mean of each column:")
print(column_means)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Mean of each column:
[4. 5. 6.]


## 47. Array Broadcasting

In [104]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array2 = np.array([2, 3, 4])

result = array1 * array2

print("Array 1:")
print(array1, "\n")

print("Array 2:")
print(array2, "\n")

print("Result of element-wise multiplication:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Array 2:
[2 3 4] 

Result of element-wise multiplication:
[[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]


# pandas section

In [105]:
import pandas as pd

## 48. DataFrame Creation

In [111]:
# method 1: create a dictionary and convert it to DataFrame
# Create a dictionary with column names and data
data = {
    'Name': ['Jafar', 'Taghi', 'Mammad', 'Ali'],
    'Age': [25, 30, 28, 32],
    'Country': ['USA', 'Canada', 'UK', 'Australia']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
df

Name  Age    Country
0   Jafar   25        USA
1   Taghi   30     Canada
2  Mammad   28         UK
3     Ali   32  Australia

In [112]:
# Method 2: Read data from csv into DataFrame and convert to dict and then return to DataFrame
# Load the dataset from a CSV file
df = pd.read_csv('cancer.csv')

# Convert the DataFrame to a dictionary
data_dict = df.to_dict()

# Create a DataFrame from the dictionary
df = pd.DataFrame(data_dict)
df

State  Total.Rate  Total.Number  Total.Population  \
0                Alabama       214.2       71529.0        33387205.0   
1                 Alaska       128.1        6361.0         4966180.0   
2                Arizona       165.6       74286.0        44845598.0   
3               Arkansas       223.9       45627.0        20382448.0   
4             California       150.9      393980.0       261135696.0   
5               Colorado       139.0       49035.0        35267734.0   
6            Connecticut       190.5       47567.0        24975889.0   
7               Delaware       210.2       13233.0         6295263.0   
8   District of Columbia       182.1        7730.0         4245359.0   
9                Florida       219.2      289905.0       132277071.0   
10               Georgia       159.4      108222.0        67890652.0   
11                Hawaii       166.0       15812.0         9526083.0   
12                 Idaho       162.1       17756.0        10954295.0   
13              Illinois       189.2      169730.0        89696961.0   
14               Indiana       202.7       91978.0        45372690.0   
15                  Iowa       210.3       44835.0        21322082.0   
16                Kansas       188.9       37644.0        19928783.0   
17              Kentucky       226.3       68675.0        30348057.0   
18             Louisiana       202.9       64194.0        31638386.0   
19                 Maine       239.1       22240.0         9301182.0   
20              Maryland       179.3       72603.0        40483979.0   
21         Massachusetts       197.8       90756.0        45892272.0   
22              Michigan       205.3      142458.0        69388573.0   
23             Minnesota       178.4       66328.0        37183729.0   
24           Mississippi       211.4       43874.0        20756872.0   
25              Missouri       211.2       88348.0        41838390.0   
26               Montana       196.1       13593.0         6933023.0   
27              Nebraska       187.5       23977.0        12785524.0   
28                Nevada       167.9       31758.0        18912307.0   
29         New Hampshire       197.9       18256.0         9223389.0   
30            New Jersey       189.9      116836.0        61521555.0   
31            New Mexico       163.2       23425.0        14349762.0   
32              New York       183.2      248572.0       135716524.0   
33        North Carolina       188.7      125783.0        66669069.0   
34          North Dakota       189.1        8990.0         4754903.0   
35                  Ohio       217.8      175847.0        80741243.0   
36              Oklahoma       209.4       54930.0        26229144.0   
37                Oregon       199.1       53430.0        26832116.0   
38          Pennsylvania       227.7      202230.0        88825682.0   
39          Rhode Island       211.2       15570.0         7371636.0   
40        South Carolina       202.6       65561.0        32366134.0   
41          South Dakota       196.2       11212.0         5714307.0   
42             Tennessee       213.1       94678.0        44430836.0   
43                 Texas       145.8      257000.0       176270421.0   
44                  Utah        98.5       19022.0        19321462.0   
45               Vermont       211.6        9261.0         4377262.0   
46              Virginia       177.1       99278.0        56054333.0   
47            Washington       175.9       82864.0        47114240.0   
48         West Virginia       254.6       32950.0        12940212.0   
49             Wisconsin       197.5       78578.0        39788899.0   
50               Wyoming       167.9        6603.0         3931624.0   

    Rates.Age.< 18  Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0              2.0             18.5            244.7          1017.8   
1              1.7             11.8            170.9           965.2   
2              2.5             13.6            173.6      

## 49. Data Exploration

In [114]:
df = pd.read_csv('cancer.csv')
print(df.head())

        State  Total.Rate  Total.Number  Total.Population  Rates.Age.< 18  \
0     Alabama       214.2       71529.0        33387205.0             2.0   
1      Alaska       128.1        6361.0         4966180.0             1.7   
2     Arizona       165.6       74286.0        44845598.0             2.5   
3    Arkansas       223.9       45627.0        20382448.0             2.3   
4  California       150.9      393980.0       261135696.0             2.6   

   Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0             18.5            244.7          1017.8   
1             11.8            170.9           965.2   
2             13.6            173.6           840.2   
3             17.6            250.1          1048.3   
4             13.7            163.7           902.4   

   Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
0                            2.0                          2.1  ...   
1                            0.0                          0.0  ...

## 50. Data Selection and Indexing

In [116]:
df = pd.read_csv('cancer.csv')

# Select State column
column = df['State']

print(column)

0                  Alabama
1                   Alaska
2                  Arizona
3                 Arkansas
4               California
5                 Colorado
6              Connecticut
7                 Delaware
8     District of Columbia
9                  Florida
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
14                 Indiana
15                    Iowa
16                  Kansas
17                Kentucky
18               Louisiana
19                   Maine
20                Maryland
21           Massachusetts
22                Michigan
23               Minnesota
24             Mississippi
25                Missouri
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
35                    Ohio
36                Oklahoma
3

## 51. Data Manipulation

In [117]:
df = pd.read_csv('cancer.csv')
sorted_df = df.sort_values('State')
print(sorted_df)

                   State  Total.Rate  Total.Number  Total.Population  \
0                Alabama       214.2       71529.0        33387205.0   
1                 Alaska       128.1        6361.0         4966180.0   
2                Arizona       165.6       74286.0        44845598.0   
3               Arkansas       223.9       45627.0        20382448.0   
4             California       150.9      393980.0       261135696.0   
5               Colorado       139.0       49035.0        35267734.0   
6            Connecticut       190.5       47567.0        24975889.0   
7               Delaware       210.2       13233.0         6295263.0   
8   District of Columbia       182.1        7730.0         4245359.0   
9                Florida       219.2      289905.0       132277071.0   
10               Georgia       159.4      108222.0        67890652.0   
11                Hawaii       166.0       15812.0         9526083.0   
12                 Idaho       162.1       17756.0        109542

## 52. Missing Data Handling

In [119]:
df = pd.read_csv('cancer.csv')
missing_values = df.isnull()
print(missing_values)

    State  Total.Rate  Total.Number  Total.Population  Rates.Age.< 18  \
0   False       False         False             False           False   
1   False       False         False             False           False   
2   False       False         False             False           False   
3   False       False         False             False           False   
4   False       False         False             False           False   
5   False       False         False             False           False   
6   False       False         False             False           False   
7   False       False         False             False           False   
8   False       False         False             False           False   
9   False       False         False             False           False   
10  False       False         False             False           False   
11  False       False         False             False           False   
12  False       False         False             Fal

## 53. Grouping and Aggregation

In [124]:
df = pd.read_csv('cancer.csv')

# Group the DataFrame by a State column and calculate the mean, sum, or count of Total.Number
grouped_data = df.groupby('State')['Total.Number'].agg(['mean', 'sum', 'count'])

print(grouped_data)

                          mean       sum  count
State                                          
Alabama                71529.0   71529.0      1
Alaska                  6361.0    6361.0      1
Arizona                74286.0   74286.0      1
Arkansas               45627.0   45627.0      1
California            393980.0  393980.0      1
Colorado               49035.0   49035.0      1
Connecticut            47567.0   47567.0      1
Delaware               13233.0   13233.0      1
District of Columbia    7730.0    7730.0      1
Florida               289905.0  289905.0      1
Georgia               108222.0  108222.0      1
Hawaii                 15812.0   15812.0      1
Idaho                  17756.0   17756.0      1
Illinois              169730.0  169730.0      1
Indiana                91978.0   91978.0      1
Iowa                   44835.0   44835.0      1
Kansas                 37644.0   37644.0      1
Kentucky               68675.0   68675.0      1
Louisiana              64194.0   64194.0